#
# docker-compose.yml: Sets up Kometa and ImageMaid for managing metadata and cleaning up images in Plex Media Server.
#
# For more information about Kometa, visit: https://kometa.wiki/en/nightly/kometa/scripts/imagemaid/
# For more information about ImageMaid, visit: https://kometa.wiki/en/nightly/kometa/scripts/imagemaid/
#

#
# Docker Compose version on the target system
#
version: "2.9"

#
# Define the services section
#
services:
  #
  # Define the 'kometa' service
  #
  kometa:
    #
    # Docker image and container information
    #
    image: kometateam/kometa:${KOMETA_TAG} # Run using the nightly Kometa build
    pull_policy: always                    # Ensure that the image is always pulled
    container_name: kometa-${KOMETA_TAG}   # Append Docker image tag to container name
    restart: unless-stopped                # Restart the container unless explicitly stopped
    network_mode: bridge                   # Use the default bridge network

    #
    # Define the container environment
    #
    environment:
      - KOMETA_DEBUG=${KOMETA_DEBUG} # Toggles running with extra debug logs
      - KOMETA_RUN=${KOMETA_RUN}     # Toggles running Kometa right away
      - TZ=${TZ}                     # Set the timezone to America/New_York

    #
    # Mount host directories into the container
    #
    volumes:
      - /volume2/docker/kometa-config:/config:rw

  #
  # Define the 'image-maid' service
  #
  image-maid:
    #
    # Docker image and container information
    #
    image: kometateam/imagemaid:${IMAGE_MAID_TAG} # Run using the nightly Kometa build
    pull_policy: always                           # Ensure that the image is always pulled
    container_name: image-maid-${IMAGE_MAID_TAG}  # Append Docker image tag to container name
    restart: unless-stopped                       # Restart the container unless explicitly stopped
    network_mode: bridge                          # Use the default bridge network

    #
    # Define the container environment
    #
    environment:
      - TZ=${TZ} # Set the timezone to America/New_York

    #
    # Mount host directories into the container
    #
    volumes:
      - /volume2/docker/kometa-config/docker-compose/image-maid-config:/config:rw
      - /volume2/PlexMediaServer/AppData/Plex Media Server:/plex:rw
