#
# image-maid.yml: Sets up ImageMaid for for cleaning up images in Plex Media Server.
#
# For more information about ImageMaid, visit: https://kometa.wiki/en/nightly/kometa/scripts/imagemaid/
#

#
# Define the services section
#
services:
  #
  # Define the 'image-maid' service
  #
  image-maid:
    #
    # External environment variables
    #
    env_file:
      - path: image-maid.env # Environment variables for the container
        required: true       # Throw an error if the env file is missing

    #
    # Docker image and container information
    #
    image: kometateam/imagemaid:${IMAGE_MAID_TAG} # Run using the nightly Kometa build
    pull_policy: always                           # Ensure that the image is always pulled
    container_name: image-maid-${IMAGE_MAID_TAG}  # Append Docker image tag to container name
    restart: unless-stopped                       # Restart the container unless explicitly stopped
    network_mode: bridge                          # Use the default bridge network

    #
    # Define the container environment
    #
    environment:
      - TZ=${TZ} # Set the timezone to America/New_York

    #
    # Mount host directory '/volume2/docker/ImageMaid' to the container directory '/config'
    # Mount host directory '/volume2/PlexMediaServer/AppData/Plex Media Serve' to the container directory '/plex'
    #
    volumes:
      - /volume2/docker/ImageMaid/config:/config:rw
      - /volume2/PlexMediaServer/AppData/Plex Media Server:/plex:rw
